import { supabase } from "../js/supabase.js";

let historyData = [];

export async function init() {
  const historyList = document.getElementById("historyList");
  const historySearch = document.getElementById("historySearch");
  const historyExamFilter = document.getElementById("historyExamFilter");
  const historySubjectFilter = document.getElementById("historySubjectFilter");
  const historyCount = document.getElementById("historyCount");

  if (
    !historyList ||
    !historySearch ||
    !historyExamFilter ||
    !historySubjectFilter ||
    !historyCount
  ) {
    return;
  }

  function formatDate(dateValue) {
    const date = new Date(dateValue);

    return date.toLocaleDateString("en-NG", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  }

  function formatTime(seconds) {
    if (seconds === null || seconds === undefined) {
      return "—";
    }

    const totalSeconds = Number(seconds);

    if (!Number.isFinite(totalSeconds)) {
      return "—";
    }

    const minutes = Math.floor(totalSeconds / 60);
    const remainingSeconds = totalSeconds % 60;

    if (minutes === 0) {
      return `${remainingSeconds}s`;
    }

    return `${minutes}m ${String(remainingSeconds).padStart(2, "0")}s`;
  }

  function getScoreClass(score) {
    if (score >= 70) {
      return "good";
    }

    if (score >= 50) {
      return "average";
    }

    return "poor";
  }

  function escapeHTML(value) {
    return String(value)
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;")
      .replaceAll("'", "&#039;");
  }

  function showLoading() {
    historyList.innerHTML = `
      <div class="history-loading">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 100 100"
          preserveAspectRatio="xMidYMid"
          width="26px"
          height="26px"
          style="
            shape-rendering: auto;
            display: block;
            background: rgba(255, 255, 255, 0);
            margin: 0 auto 12px;
          "
          xmlns:xlink="http://www.w3.org/1999/xlink"
        >
          <g>
            <circle
              stroke-dasharray="188.49555921538757 64.83185307179586"
              r="40"
              stroke-width="9"
              stroke="#2563eb"
              fill="none"
              cy="50"
              cx="50"
            >
              <animateTransform
                keyTimes="0;1"
                values="0 50 50;360 50 50"
                dur="1.0526315789473684s"
                repeatCount="indefinite"
                type="rotate"
                attributeName="transform"
              ></animateTransform>
            </circle>
            <g></g>
          </g>
          <!-- [ldio] generated by https://loading.io -->
        </svg>
        <p>Loading history...</p>
      </div>
    `;

    historyCount.textContent = "";
  }

  function showEmpty() {
    historyList.innerHTML = `
      <div class="history-empty">
        <div class="history-empty-icon">↺</div>
        <h3>No practice history yet</h3>
        <p>Complete a practice session and it will appear here.</p>
      </div>
    `;

    historyCount.textContent = "";
  }

  function showError() {
    historyList.innerHTML = `
      <div class="history-error">
        <h3>Something went wrong</h3>
        <p>We couldn't load your practice history.</p>
      </div>
    `;

    historyCount.textContent = "";
  }

  function createHistoryCard(item) {
    const subject = escapeHTML(
      String(item.subject || "")
        .charAt(0)
        .toUpperCase() + String(item.subject || "").slice(1),
    );
    const examType = escapeHTML(item.exam_type || "Unknown");
    const score = Number(item.score_percentage) || 0;
    const correct = Number(item.correct_answers) || 0;
    const total = Number(item.total_questions) || 0;

    return `
      <article class="history-card">

        <div class="history-card-left">

          <div class="history-subject">
            ${subject}
          </div>

          <div class="history-meta">

            <span class="history-exam">
              ${examType}
            </span>

            <span class="history-date">
              ${formatDate(item.completed_at)}
            </span>

          </div>

        </div>

        <div class="history-score ${getScoreClass(score)}">
          ${score}%
        </div>

        <div class="history-info">

          <span>
            ${correct}/${total} questions
          </span>

          <span>
            ${formatTime(item.time_taken)}
          </span>

        </div>

      </article>
    `;
  }

  function renderHistory() {
    const searchValue = historySearch.value.trim().toLowerCase();
    const selectedExam = historyExamFilter.value;
    const selectedSubject = historySubjectFilter.value;

    const filteredHistory = historyData.filter((item) => {
      const subject = String(item.subject || "").toLowerCase();
      const examType = String(item.exam_type || "");

      const matchesSearch = !searchValue || subject.includes(searchValue);

      const matchesExam = selectedExam === "all" || examType === selectedExam;

      const matchesSubject =
        selectedSubject === "all" || item.subject === selectedSubject;

      return matchesSearch && matchesExam && matchesSubject;
    });

    if (!filteredHistory.length) {
      historyList.innerHTML = `
        <div class="history-empty">
          <h3>No matching practices</h3>
          <p>Try changing your search or filters.</p>
        </div>
      `;

      historyCount.textContent = "";
      return;
    }

    historyList.innerHTML = filteredHistory.map(createHistoryCard).join("");

    historyCount.textContent = `${filteredHistory.length} practice${
      filteredHistory.length === 1 ? "" : "s"
    }`;
  }

  function populateFilters() {
    const subjects = [
      ...new Set(historyData.map((item) => item.subject).filter(Boolean)),
    ];

    subjects.sort((a, b) => a.localeCompare(b));

    historySubjectFilter.innerHTML = `
      <option value="all">All Subjects</option>

      ${subjects
        .map(
          (subject) => `
            <option value="${escapeHTML(subject)}">
              ${escapeHTML(subject)}
            </option>
          `,
        )
        .join("")}
    `;

    const examTypes = [
      ...new Set(historyData.map((item) => item.exam_type).filter(Boolean)),
    ];

    examTypes.sort((a, b) => a.localeCompare(b));

    historyExamFilter.innerHTML = `
      <option value="all">All Exams</option>

      ${examTypes
        .map(
          (examType) => `
            <option value="${escapeHTML(examType)}">
              ${escapeHTML(examType)}
            </option>
          `,
        )
        .join("")}
    `;
  }

  async function loadHistory() {
    showLoading();

    const {
      data: { user },
      error: userError,
    } = await supabase.auth.getUser();

    if (userError || !user) {
      showError();
      return;
    }

    const { data, error } = await supabase
      .from("practice_history")
      .select(
        `
        id,
        subject,
        exam_type,
        total_questions,
        correct_answers,
        score_percentage,
        time_taken,
        completed_at
      `,
      )
      .eq("user_id", user.id)
      .order("completed_at", {
        ascending: false,
      });

    if (error) {
      console.error("History error:", error);
      showError();
      return;
    }

    historyData = data || [];

    if (!historyData.length) {
      showEmpty();
      return;
    }

    populateFilters();
    renderHistory();
  }

  historySearch.addEventListener("input", renderHistory);
  historyExamFilter.addEventListener("change", renderHistory);
  historySubjectFilter.addEventListener("change", renderHistory);

  await loadHistory();
}
